/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTimetableRouteImport } from './routes/_app/timetable'
import { Route as AppMoreRouteImport } from './routes/_app/more'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppGateRouteImport } from './routes/_app/gate'
import { Route as AppGateSuccessRouteImport } from './routes/_app/gate.success'
import { Route as AppClassClassIdRouteImport } from './routes/_app/class.$classId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppGateRoute = AppGateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => AppRoute,
} as any)
const AppGateSuccessRoute = AppGateSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AppGateRoute,
} as any)
const AppClassClassIdRoute = AppClassClassIdRouteImport.update({
  id: '/class/$classId',
  path: '/class/$classId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/gate': typeof AppGateRouteWithChildren
  '/history': typeof AppHistoryRoute
  '/home': typeof AppHomeRoute
  '/more': typeof AppMoreRoute
  '/timetable': typeof AppTimetableRoute
  '/class/$classId': typeof AppClassClassIdRoute
  '/gate/success': typeof AppGateSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/gate': typeof AppGateRouteWithChildren
  '/history': typeof AppHistoryRoute
  '/home': typeof AppHomeRoute
  '/more': typeof AppMoreRoute
  '/timetable': typeof AppTimetableRoute
  '/class/$classId': typeof AppClassClassIdRoute
  '/gate/success': typeof AppGateSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/gate': typeof AppGateRouteWithChildren
  '/_app/history': typeof AppHistoryRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/more': typeof AppMoreRoute
  '/_app/timetable': typeof AppTimetableRoute
  '/_app/class/$classId': typeof AppClassClassIdRoute
  '/_app/gate/success': typeof AppGateSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/gate'
    | '/history'
    | '/home'
    | '/more'
    | '/timetable'
    | '/class/$classId'
    | '/gate/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/gate'
    | '/history'
    | '/home'
    | '/more'
    | '/timetable'
    | '/class/$classId'
    | '/gate/success'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/gate'
    | '/_app/history'
    | '/_app/home'
    | '/_app/more'
    | '/_app/timetable'
    | '/_app/class/$classId'
    | '/_app/gate/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/timetable': {
      id: '/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gate': {
      id: '/_app/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof AppGateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gate/success': {
      id: '/_app/gate/success'
      path: '/success'
      fullPath: '/gate/success'
      preLoaderRoute: typeof AppGateSuccessRouteImport
      parentRoute: typeof AppGateRoute
    }
    '/_app/class/$classId': {
      id: '/_app/class/$classId'
      path: '/class/$classId'
      fullPath: '/class/$classId'
      preLoaderRoute: typeof AppClassClassIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppGateRouteChildren {
  AppGateSuccessRoute: typeof AppGateSuccessRoute
}

const AppGateRouteChildren: AppGateRouteChildren = {
  AppGateSuccessRoute: AppGateSuccessRoute,
}

const AppGateRouteWithChildren =
  AppGateRoute._addFileChildren(AppGateRouteChildren)

interface AppRouteChildren {
  AppGateRoute: typeof AppGateRouteWithChildren
  AppHistoryRoute: typeof AppHistoryRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMoreRoute: typeof AppMoreRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppClassClassIdRoute: typeof AppClassClassIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGateRoute: AppGateRouteWithChildren,
  AppHistoryRoute: AppHistoryRoute,
  AppHomeRoute: AppHomeRoute,
  AppMoreRoute: AppMoreRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppClassClassIdRoute: AppClassClassIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
